name: 'Update Modrinth Description'

on:
  push:
    branches: [ 'main' ]
    paths:
      "**/README.md"
  workflow_dispatch:
jobs:
  modrinth-desc:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
    - uses: funnyboy-roks/modrinth-auto-desc@v1.5
      with:
        auth-token: ${{ secrets.MODRINTH_API_TOKEN }}
        slug: 'forf'